### ISSUE TITLE
Is this library compatible with Windows 10?

### ISSUE THREAD

**Issue by RossVertizan** [executablebooks/sphinx-copybutton#79]
Hi,

I have tried installing on Windows 10 and I get errors.  First I did this:

```
python -m pip install sphinx-copybutton
Collecting sphinx-copybutton
  Downloading https://files.pythonhosted.org/packages/23/28/5b32ff11b8dda007cafe6fff399758b222c757bcf3e7bd4b92c771e4b772/sphinx-copybutton-0.2.11.tar.gz (110kB)
    100% |################################| 112kB 2.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ross\appdata\local\temp\pip-install-ehoyds\sphinx-copybutton\setup.py", line 2, in <module>
        from pathlib import Path
    ImportError: No module named pathlib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\ross\appdata\local\temp\pip-install-ehoyds\sphinx-copybutton\
```
So then I did this:

```
python -m pip install sphinx-copybutton
Collecting sphinx-copybutton
  Downloading https://files.pythonhosted.org/packages/23/28/5b32ff11b8dda007cafe6fff399758b222c757bcf3e7bd4b92c771e4b772/sphinx-copybutton-0.2.11.tar.gz (110kB)
    100% |################################| 112kB 2.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ross\appdata\local\temp\pip-install-ehoyds\sphinx-copybutton\setup.py", line 2, in <module>
        from pathlib import Path
    ImportError: No module named pathlib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\ross\appdata\local\temp\pip-install-ehoyds\sphinx-copybutton\
```
and then this:
```
python -m pip install sphinx-copybutton
Collecting sphinx-copybutton
  Using cached https://files.pythonhosted.org/packages/23/28/5b32ff11b8dda007cafe6fff399758b222c757bcf3e7bd4b92c771e4b772/sphinx-copybutton-0.2.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ross\appdata\local\temp\pip-install-uurvx2\sphinx-copybutton\setup.py", line 23, in <module>
        for line in init.read_text().split("\n"):
    AttributeError: 'WindowsPath' object has no attribute 'read_text'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\ross\appdata\local\temp\pip-install-uurvx2\sphinx-copybutton\
```

and now I'm a little bit stuck.

For information, this is the Python version I am using:
```
> python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Thanks in advance for any help you can offer.

**Comment by choldgraf** [comment]
Hey there - sphinx-copybutton requires Python >= 3.6, I think that's where your problems are coming from
